name: debug_rest_skillet_headers
label: REST GET with custom headers

description: |
  This skillet demonstrates a simple REST api call with custom headers and JSON output capturing using jsonpath. This
  Skillet also specifies an 'output_template' label. This informs skilletlib to load, parse, and render the template
  file specified. The rendered output template is added to the skillet output in as the 'output_template' attribute.

type: rest

labels:
  collection:
    - Example Skillets
  output_template: output.j2

variables:
  - name: api_key
    default:
    description: Prisma Cloud API Key
    type_hint: text

snippets:
  - name: Retrieve Remote Network Service IP from Prisma Access
    path: https://api.gpcloudservice.com/getAddrList/latest?fwType=gpcs_remote_network&addrType=public_ip
    operation: GET
    headers:
      header-api-key: '{{ api_key }}'
    output_type: json
    outputs:
      - name: status
        capture_pattern: $.status
      - name: fwType
        capture_pattern: $.result.fwType
      - name: addrList
        capture_pattern: $.result.addrList
