name: panoply_panorama_baseline_90
label: Panorama Baseline Configuration for Version 9.0

description: |
  Loads a configuration that is essentially a factory default plus admin username, password, and IP information
type: template
labels:
  collection:
    - Panoply Utility Skillets

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: ADMINISTRATOR_USERNAME
    description: Admin Username
    default: admin
    type_hint: text
  - name: ADMINISTRATOR_PASSWORD
    description: Admin Password
    default: admin
    type_hint: password
  - name: PANORAMA_TYPE
    description: Panorama management IP type
    default: static
    type_hint: dropdown
    dd_list:
      - key: static
        value: static
      - key: cloud dhcp
        value: cloud
  - name: PANORAMA_NAME
    description: Panorama hostname
    default: panorama-90
    type_hint: text
  - name: PANORAMA_IP
    description: Panorama IP
    default: 192.168.55.7
    type_hint: ip_address
  - name: PANORAMA_MASK
    description: Panorama netmask
    default: 255.255.255.0
    type_hint: ip_address
  - name: PANORAMA_DG
    description: Panorama default gateway
    default: 192.168.55.2
    type_hint: ip_address
# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: baseline
    file: baseline_90.xml



