name: inline_template_example
label: Inline Template Example
description: Simple Example to show how a template skillet can be used with an inline template element
type: template
labels:
  collection:
    - Example Skillets

variables:
  - name: SOME_VARIABLE
    description: Some VARIABLE
    default: present
    type_hint: text

snippets:
  - name: config_template
    element: |
      Templates can be defined inline using the 'element' attribute. Variable is {{ SOME_VARIABLE }}.