#
# Example When Conditional
#
# In order to properly validate a config, it is often necessary to convert the XML structure to an object, which
# can then be used in jinja expression to perform basic logic and validation. These examples demonstrate how
# skillets are optimized for this task.
#

name: example-output-template
label: Example of how to use output_template to add customized output

description: |
  This example Skillet shows how to add an additional 'template' attribute to the output. The value of the 'template'
  attribute is the result of rendering the configured jinja template using the skillet outputs as the context. Any
  and all captured values are available for use in the template engine.

type: pan_validation
labels:
  collection:
    - Example Skillets
    - Validation
  output_template: output.j2

variables:
  - name: SOME_VARIABLE
    description: Some VARIABLE
    default: present
    type_hint: text

snippets:
  - name: show_device_system
    cmd: parse
    variable: config
    outputs:
      - name: update_schedule_object
        capture_object: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule

  - name: update_schedule_configured
    label: Ensure Update Schedules are Configured
    test: update_schedule_object is not none
    documentation_link: https://docs.paloaltonetworks.com/pan-os/8-0/pan-os-new-features/content-inspection-features/telemetry-and-threat-intelligence-sharing

  - name: update_schedule_stats_service_configured
    when: update_schedule_object is not none
    label: Ensure Statistics Service is enabled
    test: update_schedule_object| tag_present('update-schedule.statistics-service')
    documentation_link: https://docs.paloaltonetworks.com/pan-os/8-0/pan-os-new-features/content-inspection-features/telemetry-and-threat-intelligence-sharing